require_relative './base.rb'

Columns.define do
  category 'year'
  category 'month'
  category 'day'
  category 'day_of_week'
  category 'carrier'
  category 'tail_num'
  category 'flight_num'
  category 'origin_airport'
  category 'origin_fips'
  category 'dest_airport'
  time     'sched_dep_time'
  target   'dep_delay'
  target   'dep_delay_15'
  target   'dep_delay_group'
  time     'sched_arr_time'
  number   'arr_delay'
  category 'cancelled'
  category 'diverted'
  time     'sched_arr_time'
  number   'sched_elapsed_time'
  number   'distance'
end
