require_relative './base.rb'

Columns.define do
  category 'year'
  category 'month'
  category 'day'
  category 'day_of_week'
  category 'origin_airport'
  category 'dest_airport'
  category 'sched_dep_hr'
  category 'sched_dep_min'
  category 'sched_arr_hr'
  category 'sched_arr_min'
  number   'sched_elapsed_time'
  category 'carrier'
  number   'distance'
  number   'prev_arr_delay'
  target   'dep_delay'
  target   'dep_delay_15'
  target   'dep_delay_group'
end
