require_relative './base.rb'

Columns.define do
  category 'dep_year'
  category 'dep_month'
  category 'dep_day'
  category 'dep_dow'
  category 'dep_hr'
  category 'dep_min'
  category 'orig_airport'

  category 'arr_year'
  category 'arr_month'
  category 'arr_day'
  category 'arr_dow'
  category 'arr_hr'
  category 'arr_min'
  category 'dest_airport'

  number   'sched_elapsed_time'
  category 'carrier'
  number   'distance'
  number   'prev_arr_delay'

  number   'orig_air_temp'
  number   'orig_dew_point'
  number   'orig_pressure'
  direction_degrees 'orig_wind_dir'
  number   'orig_wind_speed'
  category 'orig_sky_cond'
  number   'orig_precip_hr'
  number   'orig_precip_sixhr'

  number   'dest_air_temp'
  number   'dest_dew_point'
  number   'dest_pressure'
  direction_degrees 'dest_wind_dir'
  number   'dest_wind_speed'
  category 'dest_sky_cond'
  number   'dest_precip_hr'
  number   'dest_precip_sixhr'

  target   'dep_delay'
  target   'dep_delay_15'
  target   'dep_delay_group'
end
